/*form 1*/
ALTER TABLE `tbl_meanf1t1` CHANGE `mn1` `mn1` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf1t2` CHANGE `mn1` `mn1` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf1t3` CHANGE `mn1` `mn1` DECIMAL(65,3) NULL DEFAULT NULL;

ALTER TABLE `tbl_meanf1t1` CHANGE `mn2` `mn2` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf1t2` CHANGE `mn2` `mn2` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf1t3` CHANGE `mn2` `mn2` DECIMAL(65,3) NULL DEFAULT NULL;

ALTER TABLE `tbl_meanf1t1` CHANGE `mn3` `mn3` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf1t2` CHANGE `mn3` `mn3` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf1t3` CHANGE `mn3` `mn3` DECIMAL(65,3) NULL DEFAULT NULL;

ALTER TABLE `tbl_meanf1t1` CHANGE `mn4` `mn4` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf1t2` CHANGE `mn4` `mn4` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf1t3` CHANGE `mn4` `mn4` DECIMAL(65,3) NULL DEFAULT NULL;

/*form 2*/
ALTER TABLE `tbl_meanf2t1` CHANGE `mn1` `mn1` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf2t2` CHANGE `mn1` `mn1` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf2t3` CHANGE `mn1` `mn1` DECIMAL(65,3) NULL DEFAULT NULL;

ALTER TABLE `tbl_meanf2t1` CHANGE `mn2` `mn2` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf2t2` CHANGE `mn2` `mn2` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf2t3` CHANGE `mn2` `mn2` DECIMAL(65,3) NULL DEFAULT NULL;

ALTER TABLE `tbl_meanf2t1` CHANGE `mn3` `mn3` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf2t2` CHANGE `mn3` `mn3` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf2t3` CHANGE `mn3` `mn3` DECIMAL(65,3) NULL DEFAULT NULL;

ALTER TABLE `tbl_meanf2t1` CHANGE `mn4` `mn4` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf2t2` CHANGE `mn4` `mn4` DECIMAL(65,3) NULL DEFAULT NULL;
ALTER TABLE `tbl_meanf2t3` CHANGE `mn4` `mn4` DECIMAL(65,3) NULL DEFAULT NULL;